function [time,start0,end0,time1,time2,time3]=calculation_3missle(cast_time,explode_time,explode_time1,explode_time2,velocity_smoke_x,velocity_smoke_y,interval1,interval2, ...
    distance_x1,distance_y1,distance_z1,...
    distance_x2,distance_y2,distance_z2,...
    distance_x3,distance_y3,distance_z3,...
    distance_smoke_x,distance_smoke_y,distance_smoke_z,...
    velocity_missle_x1,velocity_missle_y1,velocity_missle_z1,...
    velocity_missle_x2,velocity_missle_y2,velocity_missle_z2,...
    velocity_missle_x3,velocity_missle_y3,velocity_missle_z3)
    

    [time1,start1,end1]=calculation_3smoke(cast_time,explode_time,explode_time1,explode_time2,velocity_smoke_x,velocity_smoke_y,interval1,interval2,...
                                                       distance_x1,distance_y1,distance_z1, ...
                                                       distance_smoke_x,distance_smoke_y,distance_smoke_z, ...
                                                       velocity_missle_x1,velocity_missle_y1,velocity_missle_z1);
    [time2,start2,end2]=calculation_3smoke(cast_time,explode_time,explode_time1,explode_time2,velocity_smoke_x,velocity_smoke_y,interval1,interval2,...
                                                       distance_x2,distance_y2,distance_z2, ...
                                                       distance_smoke_x,distance_smoke_y,distance_smoke_z, ...
                                                       velocity_missle_x2,velocity_missle_y2,velocity_missle_z2);
    [time3,start3,end3]=calculation_3smoke(cast_time,explode_time,explode_time1,explode_time2,velocity_smoke_x,velocity_smoke_y,interval1,interval2,...
                                                       distance_x3,distance_y3,distance_z3, ...
                                                       distance_smoke_x,distance_smoke_y,distance_smoke_z, ...
                                                       velocity_missle_x3,velocity_missle_y3,velocity_missle_z3);
    time=time1+time2+time3; 
    start0=min(min(start1,start2),start3);
    end0=max(max(end1,end2),end3);
    
end